# Providers
# YAML, MYSQL, MEMORY
provider: YAML

# Target server for premium users
target-server: "lobby"

mysql:
  host: localhost
  port: 3306
  database: authme_premium
  username: root
  password: password